# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: df500c43fd7697f7111aab41e4ffa2e21845c64935ae5720062aab216eb9b4e30bad6fc8e85b5d828a9dfdeaf962006c55f48423d41a105d27c1ad5f6508e13e

test:
  secret_key_base: 9f7d8be7ebaaed78123a3b494b2b7156e53daeb7331e065cd264d825c437c104043cfdd2de7a658d220d5f323601b916899417ee6f2531779279d13a2b6747a1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
